import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Token Deployer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
              <ToastContainer />

      <body className={inter.className}>{children}</body>
    </html>
  )
}
